### ISSUE TITLE
NodeJS cannot load minified file

### ISSUE THREAD

**Issue by DaJuukes** [chartjs/chartjs-chart-financial#40] opened 2018-08-07 23:29 UTC
Hey. I've been toying with this all day to no avail so far. I've been using chartjs-node with no issues but I can't even load chartjs-chart-financial.

I've built the library and even used their pre-provided one, but whenever I require() the file, it throws errors such as:
- Window is not defined
- Chart.Ticks is undefined

These errors are on the loading of this file, not even the execution of the function.

I can't seem to figure out what's wrong and all my workarounds aren't getting anywhere. I feel like I'm missing something right in front of my face, too.

**Comment by benmccann** [comment] 2018-10-15 17:56
At some point I'll publish this on npm, which should fix this issue. Closing as duplicate of https://github.com/chartjs/chartjs-chart-financial/issues/35

**Closed by benmccann** 2018-10-15 17:56 UTC

**Comment by Techn1x** [comment] 2018-11-16 05:42
@DaJuukes I had the same issue with Chart.Ticks when I imported Chart.Financial.js directly. Turns out I was only using Chart.js 2.7.1, and this addon requires Chart.js 2.7.3
